// client/src/constants/tagOptions.js

export const TAG_OPTIONS = [
  { value: "array", label: "Array" },
  { value: "string", label: "String" },
  { value: "linked-list", label: "Linked List" },
  { value: "doubly-linked-list", label: "Doubly Linked List" },
  { value: "stack", label: "Stack" },
  { value: "queue", label: "Queue" },
  { value: "tree", label: "Tree" },
  { value: "binary-tree", label: "Binary Tree" },
  { value: "binary-search-tree", label: "BST" },
  { value: "heap", label: "Heap" },
  { value: "hash-table", label: "Hash Table" },
  { value: "graph", label: "Graph" },
  { value: "depth-first-search", label: "DFS" },
  { value: "breadth-first-search", label: "BFS" },
  { value: "topological-sort", label: "Topological Sort" },
  { value: "dynamic-programming", label: "DP" },
  { value: "memoization", label: "Memoization" },
  { value: "greedy", label: "Greedy" },
  { value: "two-pointers", label: "Two Pointers" },
  { value: "sliding-window", label: "Sliding Window" },
  { value: "backtracking", label: "Backtracking" },
  { value: "bit-manipulation", label: "Bit Manipulation" },
  { value: "math", label: "Math" },
  { value: "geometry", label: "Geometry" },
  { value: "sorting", label: "Sorting" },
  { value: "searching", label: "Searching" },
  { value: "recursion", label: "Recursion" },
  { value: "design", label: "Design" },
  { value: "concurrency", label: "Concurrency" },
  { value: "bitmask", label: "Bitmask" },
  { value: "union-find", label: "Union-Find" },
  { value: "trie", label: "Trie" },
  { value: "divide-and-conquer", label: "D&C" },
  { value: "matrix", label: "Matrix" },
];
